[build]
    functions = "functions"

[[redirects]]
    from = "/auth/profile-image/*"
    to = "https://your-api-domain.com/auth/profile-image/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/api/*"
    to = "https://your-api-domain.com/api/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
